config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  
  def index
    @tasks = current_user.tasks
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      #flash message
      redirect_to tasks_path
    else
      #flash message
      render :new
    end
  end

  def edit
  end
  
  def update
    if @task.update(task_params)
      #flash message
      redirect_to tasks_path
    else
      #flash message
      render :edit
    end
  end

  def destroy
    if @task.destroy
      #flash message
      redirect_to tasks_path
    else
      #flash message
      render :new
    end
  end

  private

  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h3>Edit Task</h3>
<%= form_with(model: @task, local: true) do |f| %>
<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title, required: true  %>
</div>
<div class="field">
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
  <nav>
    <div class="nav-wrapper blue-grey lighten-1">
      <ul class="right hide-on-med-and-down blue-grey lighten-1">
        <li><%= link_to 'New Task', new_task_path, class: "waves-effect waves-light btn blue-grey darken-1" %></li>
      </ul>
    </div>
  </nav>
<h4><%= "Account: #{current_user.email}" %></h4>
<hr>
  <% @tasks.each do |task|%>
  <div class="row">
    <div class="col s12 m4">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= task.title %></span>
          <p><%= task.description %></p>
        </div>
        <div class="card-action">
          <%= link_to "Delete", task_path(task), method: :delete %>
          <%= link_to "Edit", edit_task_path(task) %>
        </div>
      </div>
    </div>
  </div>
   <% end %>
            
  
<%= button_to "Log out", destroy_user_session_path, method: :delete, class: "btn waves-effect waves-light blue-grey darken-1" %>

app/views/tasks/new.html.erb
<h3>New Task</h3>
<%= form_with(model: @task, local: true) do |f| %>
<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title, required: true  %>
</div>
<div class="field">
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>